### PR TITLE
First push for public QAT2 HTML documents

### PR DESCRIPTION
**Pull request by johnfial**
- This PR pushes the built HTML files exactly as they were built (after _make clean_ and _make html_) via the main branch from the working documentation repo. 
- By my count: 380 Files, 68 Folders, 89.8 MB (94,257,152 bytes).- 
- Two approvals + merging will make the documentation public!

### CODE REVIEW

**Comment by johnfial** [comment]
I'm not sure if we'll build like this each time, but one way I might approach this (annoying mess of files) PR would be to build the files myself, then compare the structures with our branch here vs _main_ on the other repo. Just an idea.

**Review by diego-villalobos — COMMENTED** [review]
I see all files were generated, even for the sections not referenced in the index.rst file. Unsure if their content will be visible if a search in the website is done... should we test it internally before releasing to public?

**Comment by jdschuet** [comment]
agreed.. additional testing required.. and we need to get Linux Release notes included

**Comment by johnfial** [comment]
> I see all files were generated, even for the sections not referenced in the index.rst file. Unsure if their content will be visible if a search in the website is done... should we test it internally before releasing to public?

Yes, they are. Gotta figure this out...

> agreed.. additional testing required.. and we need to get Linux Release notes included

Yes, also a problem!

**Pull request closed without merging**
