### PR TITLE
first public push

### PR DESCRIPTION
**Pull request by johnfial**
- This PR pushes the built HTML files exactly as they were built (after make clean and make html) via the main branch from the working documentation repo.
- Two approvals + merging will make the documentation public!
- By my count, 168 files, 25 folders, 82.7 MB (86,788,861 bytes)

### CODE REVIEW

**Review by diego-villalobos — COMMENTED** [review]
@johnfial - I think the "new" files under the Linux RN have to be "put" into the draft ones, isn't it? I'm referring to the in-tree files and qatlib file. Also (I just realized about them), the revision_history_dc and revision_history_lac files which are used for the API manuals have to be excluded, they are under /doc.

**Comment by johnfial** [comment]
> @johnfial - I think the "new" files under the Linux RN have to be "put" into the draft ones, isn't it? I'm referring to the in-tree files and qatlib file. Also (I just realized about them), the revision_history_dc and revision_history_lac files which are used for the API manuals have to be excluded, they are under /doc.

For your first point -- are you talking about the files at _documentation_ PR 43?

For your second point (API Ref rev_histories), you are correct, thy should be invisible by default. However, it's easily correctable, but if I don't do it on this PR, it's no major concern because that information is already in the current public API Ref Manual PDFs. Good catch, though!

**Comment by diego-villalobos** [comment]
> > @johnfial - I think the "new" files under the Linux RN have to be "put" into the draft ones, isn't it? I'm referring to the in-tree files and qatlib file. Also (I just realized about them), the revision_history_dc and revision_history_lac files which are used for the API manuals have to be excluded, they are under /doc.
> 
> For your first point -- are you talking about the files at _documentation_ PR 43?
> 
> For your second point (API Ref rev_histories), you are correct, thy should be invisible by default. However, it's easily correctable, but if I don't do it on this PR, it's no major concern because that information is already in the current public API Ref Manual PDFs. Good catch, though!

I'm referring to the files added in _documentation_ PR 12:

- in_tree_firmware_RN.rst
- in_tree_kernel_driver_RN.rst
- qatlib_RN.rst

**Comment by johnfial** [comment]
> 
> I'm referring to the files added in _documentation_ PR 12:
> 
> * in_tree_firmware_RN.rst
> * in_tree_kernel_driver_RN.rst
> * qatlib_RN.rst

Great catch. I removed these drafts and will rename them on the source repo. However, I don't consider the contents sensitive enough to warrant a "rebase" or removal of this whole PR.

@jdschuet  could you kindly review this PR?

**Review by diego-villalobos — APPROVED** [review]
It looks good to me!

**Review by jdschuet — CHANGES_REQUESTED** [review]
Almost perfect :)  The documents included look great.
Under the video we have videos for thermal and virt that should be removed

**Comment by johnfial** [comment]
@jdschuet  videos were removed yesterday

**Review by jdschuet — APPROVED** [review]
Amazing!

**Pull request merged**
